### ISSUE TITLE
how about speed and memory after quantized 4-bit

### ISSUE THREAD

**Issue by xiongzihua** [blueardour/model-quantization#4]

**Comment by blueardour** [comment]
Hi, @xiongzihua 

I assume you are wondering the inference speed/memory for the quantization model. 

The speed and memory benefit of the quantization depends on the platform and the quality of the code optimization. In the publication, several times and even one magnitude order speedup is reported. However, the baselines in different works are different and detailed experiment settings are generally not given. 

I ever paid effort on low-bit network acceleration on embedded devices, such as Hisilicon Kirin 970, Qualcomm 835. I compare the speed of my code with the commercial software libraries, such as SNPE. Currently, only quantization networks below 3-bit can beat the full precision (FP32 or FP16) counterparts for the whole network. I did not employ some tricks such as winograd yet, so that large margin exists for my code to be improved. To date,  4-bit models seem not appealing to me versus the commercial libraries. 

For the memory, it is related with the allocate strategies and also the network structure. In my current optimization, the input activation and weight are quantized into extreme low-bit, which can obtain one magnitude order smaller saving than the FP32 counterparts. However, the output is still in high precision (at least FP16 or INT16), which is at the same level with the 'un-quantized' models.

**Comment by xiongzihua** [comment]
excellent work, thank you for your detailed reply.

**Comment by blueardour** [comment]
Will reopen if further questions on the topic.
